### ISSUE TITLE
Add Tests to Project

### ISSUE THREAD

**Issue by mfonism** [SteinRobert/python-restcountries#8]
I'd love to write tests for this project. They'd just assert that the classmethods make requests to the correct URIs.

Are the tests necessary?

If they are, should I write them with `unittest` or `pytest`?

**Comment by SteinRobert** [comment]
Tests would be very welcome, I'd love to see tests for this project.

I'm more familiar with `pytest`, however, in the end, both are good testing frameworks.

>They'd just assert that the classmethods make requests to the correct URIs.

That could be definitely a start. An even better testing approach would be to mock the behavior of the rest countries API. There are different approaches on how to achieve this, after a quick investigation I found this one: 
https://pypi.org/project/requests-mock/

It seems reasonable to me. What do you think?

**Comment by mfonism** [comment]
I was thinking of _patching_ `requests.get`, and asserting that the classmethods call the correct URL endpoints.

But now that you've pointed out `request-mock`, I realise it's a wholesome way of testing calls to a RESTful API.

So, I'll use `request-mock` to mock out the API (when I'm free at night), and I'll submit a PR when I'm done.

**Comment by SteinRobert** [comment]
Thank you very much again.
